
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: E:/sell.log
#  level:
#    com.lous.sell.LoggerTest: debug
#  path: E:/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.30.103/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppid: wx41f14e27257c9a01
  mpAppSecret: e98ec017748812481feac6ca1494ee1b
#  mpAppid: wxd898fcb01713c658
#  mpAppSecret: 29aBa650db31472aa87800e3b0d739f2
#  mchId: 1409146202
#  mchKey: c976503d34ca432c601361f969fd8d85
#  keyPath: F://h5.p12
#  notifyUrl: http://w6wapf.natappfree.cc/sell/pay/notify
#  mpAppid: wx244b32589e71d1ed
#  mpAppSecret: 565ad6c4d533927a43d8d00fee6b3dca
#  mchId: 1509644691
#  mchKey: dJyt20180809kdiejfkdjsonk5nvbghu
#  keyPath: F://h5.p12
#  notifyUrl: http://w6wapf.natappfree.cc/sell/pay/notify