
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: E:/sell.log
#  level:
#    com.lous.sell.LoggerTest: debug
#  path: E:/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.30.103/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
